stages:
  - build
  - test
  - deploy

variables:
  APP_NAME: nextjs_app
  # Replace <your_ssh_private_key> with the contents of your SSH private key.
  # SSH_PRIVATE_KEY: <your_ssh_private_key>
  # AWS_ACCESS_KEY_ID: <your_aws_access_key>
  # AWS_SECRET_ACCESS_KEY: <your_aws_secret_access_key>
  # AWS_REGION: <your_aws_region>

before_script:
  - apt-get update -y
  - apt-get install -y nodejs npm git docker.io python3 python3-pip
  # - curl -fsSL https://get.docker.com -o get-docker.sh
  # - sh get-docker.sh
  # - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  # - eval $(ssh-agent -s)
  # - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

build:
  stage: build
  script:
    - npm ci

test:
  stage: test
  script:
    - echo "running unit tests..."
    - npm run test

deploy:
  stage: deploy
  image: npm:latest
  environment: production
  script:
    # - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    # - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    # - aws configure set region $AWS_REGION
    # Replace <your_ssh_user> with your SSH username <your_server_address> with the address of your deployment server.
    # Replace /path/to/deploy/folder with the path to the folder where you want to deploy your Next.js application on the server.
    # - ssh <your_ssh_user>@<your_server_address> "cd /path/to/deploy/folder && git pull origin master"
    # - ssh <your_ssh_user>@<your_server_address> "cd /path/to/deploy/folder && npm ci && npm run build"
    - npm run dev
    - echo "Application successfully deployed"
